Update template
hmcts/spring-boot-template pull request #359
Opened 2022-03-24 15:59 UTC by reespozzi

Team experience postgres auth issues and updating the `import:` line fixed their problems. 

Have found other examples of teams overriding this: 
-https://github.com/hmcts/send-letter-service/blob/3a527d4a0d79ff67c0378d5d8e8693dd9941e442/src/main/resources/application.yaml#L27 
-https://github.com/hmcts/em-annotation-api/blob/ddb56ba36a78e1c39a58abadfca7a581dbcda77f/src/main/resources/application.yaml#L7 
-https://github.com/hmcts/draft-store/blob/717e83858b84f950dc70ca233298e1ed5aa07593/src/main/resources/application.yaml#L16

Unsure if `team name` is the correct thing to append or it should be something else like product

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-03-24 16:07 UTC, timja requested changes
this should be `rpe` in this template and the init script updated to replace it with the product name

i.e. do it automatically for the team, don't add docs that will likely not be seen

https://github.com/hmcts/spring-boot-template/blob/master/bin/init.sh

the other template also needs updating:

https://github.com/hmcts/template-spring-boot

2022-03-24 16:08 UTC, amstevenson approved these changes

2022-03-25 09:10 UTC, reespozzi commented
Closing and looking into adding to script

2022-03-25 09:10 UTC, closed without merging

2022-03-28 09:47 UTC, reespozzi commented
Opened - https://github.com/hmcts/spring-boot-template/pull/360